/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_COMMA = 2,
  anon_sym_LF = 3,
  anon_sym_RBRACE = 4,
  aux_sym_env_decl_token1 = 5,
  anon_sym_LPAREN = 6,
  aux_sym_options_token1 = 7,
  anon_sym_RPAREN = 8,
  aux_sym_mandantory_arg_token1 = 9,
  anon_sym_LBRACK = 10,
  aux_sym_optional_arg_token1 = 11,
  anon_sym_RBRACK = 12,
  sym_class_pkg_name = 13,
  sym_env_name = 14,
  sym_KEYWORD_docclass = 15,
  sym_KEYWORD_importpkg = 16,
  sym_KEYWORD_useenv = 17,
  sym_line_comment = 18,
  sym_multiline_comment = 19,
  sym_vesti_content = 20,
  sym_statement = 21,
  sym_docclass_decl = 22,
  sym_singlepkg_decl = 23,
  sym_multipkg_decl = 24,
  sym_env_decl = 25,
  sym_options = 26,
  sym_env_arg = 27,
  sym_mandantory_arg = 28,
  sym_optional_arg = 29,
  aux_sym_vesti_content_repeat1 = 30,
  aux_sym_multipkg_decl_repeat1 = 31,
  aux_sym_env_decl_repeat1 = 32,
  aux_sym_env_decl_repeat2 = 33,
  aux_sym_options_repeat1 = 34,
  aux_sym_options_repeat2 = 35,
  aux_sym_mandantory_arg_repeat1 = 36,
  aux_sym_optional_arg_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_LF] = "\n",
  [anon_sym_RBRACE] = "}",
  [aux_sym_env_decl_token1] = "env_decl_token1",
  [anon_sym_LPAREN] = "(",
  [aux_sym_options_token1] = "options_token1",
  [anon_sym_RPAREN] = ")",
  [aux_sym_mandantory_arg_token1] = "mandantory_arg_token1",
  [anon_sym_LBRACK] = "[",
  [aux_sym_optional_arg_token1] = "optional_arg_token1",
  [anon_sym_RBRACK] = "]",
  [sym_class_pkg_name] = "class_pkg_name",
  [sym_env_name] = "env_name",
  [sym_KEYWORD_docclass] = "KEYWORD_docclass",
  [sym_KEYWORD_importpkg] = "KEYWORD_importpkg",
  [sym_KEYWORD_useenv] = "KEYWORD_useenv",
  [sym_line_comment] = "line_comment",
  [sym_multiline_comment] = "multiline_comment",
  [sym_vesti_content] = "vesti_content",
  [sym_statement] = "statement",
  [sym_docclass_decl] = "docclass_decl",
  [sym_singlepkg_decl] = "singlepkg_decl",
  [sym_multipkg_decl] = "multipkg_decl",
  [sym_env_decl] = "env_decl",
  [sym_options] = "options",
  [sym_env_arg] = "env_arg",
  [sym_mandantory_arg] = "mandantory_arg",
  [sym_optional_arg] = "optional_arg",
  [aux_sym_vesti_content_repeat1] = "vesti_content_repeat1",
  [aux_sym_multipkg_decl_repeat1] = "multipkg_decl_repeat1",
  [aux_sym_env_decl_repeat1] = "env_decl_repeat1",
  [aux_sym_env_decl_repeat2] = "env_decl_repeat2",
  [aux_sym_options_repeat1] = "options_repeat1",
  [aux_sym_options_repeat2] = "options_repeat2",
  [aux_sym_mandantory_arg_repeat1] = "mandantory_arg_repeat1",
  [aux_sym_optional_arg_repeat1] = "optional_arg_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_env_decl_token1] = aux_sym_env_decl_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_options_token1] = aux_sym_options_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_mandantory_arg_token1] = aux_sym_mandantory_arg_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_optional_arg_token1] = aux_sym_optional_arg_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_class_pkg_name] = sym_class_pkg_name,
  [sym_env_name] = sym_env_name,
  [sym_KEYWORD_docclass] = sym_KEYWORD_docclass,
  [sym_KEYWORD_importpkg] = sym_KEYWORD_importpkg,
  [sym_KEYWORD_useenv] = sym_KEYWORD_useenv,
  [sym_line_comment] = sym_line_comment,
  [sym_multiline_comment] = sym_multiline_comment,
  [sym_vesti_content] = sym_vesti_content,
  [sym_statement] = sym_statement,
  [sym_docclass_decl] = sym_docclass_decl,
  [sym_singlepkg_decl] = sym_singlepkg_decl,
  [sym_multipkg_decl] = sym_multipkg_decl,
  [sym_env_decl] = sym_env_decl,
  [sym_options] = sym_options,
  [sym_env_arg] = sym_env_arg,
  [sym_mandantory_arg] = sym_mandantory_arg,
  [sym_optional_arg] = sym_optional_arg,
  [aux_sym_vesti_content_repeat1] = aux_sym_vesti_content_repeat1,
  [aux_sym_multipkg_decl_repeat1] = aux_sym_multipkg_decl_repeat1,
  [aux_sym_env_decl_repeat1] = aux_sym_env_decl_repeat1,
  [aux_sym_env_decl_repeat2] = aux_sym_env_decl_repeat2,
  [aux_sym_options_repeat1] = aux_sym_options_repeat1,
  [aux_sym_options_repeat2] = aux_sym_options_repeat2,
  [aux_sym_mandantory_arg_repeat1] = aux_sym_mandantory_arg_repeat1,
  [aux_sym_optional_arg_repeat1] = aux_sym_optional_arg_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_env_decl_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_options_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_mandantory_arg_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_optional_arg_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_class_pkg_name] = {
    .visible = true,
    .named = true,
  },
  [sym_env_name] = {
    .visible = true,
    .named = true,
  },
  [sym_KEYWORD_docclass] = {
    .visible = true,
    .named = true,
  },
  [sym_KEYWORD_importpkg] = {
    .visible = true,
    .named = true,
  },
  [sym_KEYWORD_useenv] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_vesti_content] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_docclass_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_singlepkg_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_multipkg_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_env_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_options] = {
    .visible = true,
    .named = true,
  },
  [sym_env_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_mandantory_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_optional_arg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_vesti_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multipkg_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_env_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_env_decl_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_options_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_options_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mandantory_arg_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_optional_arg_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '%', 10,
        '(', 40,
        ')', 45,
        ',', 34,
        '[', 49,
        ']', 53,
        'd', 22,
        'i', 20,
        'u', 27,
        '{', 33,
        '}', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(61);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(44);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == ',') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '%') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == '%') ADVANCE(52);
      if (lookahead == ']') ADVANCE(53);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 8:
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == ')') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '-') ADVANCE(60);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'g') ADVANCE(58);
      END_STATE();
    case 18:
      if (lookahead == 'k') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 31:
      if (lookahead == 'v') ADVANCE(59);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_env_decl_token1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_env_decl_token1);
      if (lookahead == '%') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_env_decl_token1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '-') ADVANCE(60);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_options_token1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_options_token1);
      if (lookahead == '%') ADVANCE(44);
      if (lookahead == ')') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_options_token1);
      if (lookahead == '%') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(41);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_options_token1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '-') ADVANCE(60);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_mandantory_arg_token1);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_mandantory_arg_token1);
      if (lookahead == '%') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_mandantory_arg_token1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '-') ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_optional_arg_token1);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_optional_arg_token1);
      if (lookahead == '%') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_optional_arg_token1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '-') ADVANCE(60);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_class_pkg_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_env_name);
      if (lookahead == '*') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_env_name);
      if (lookahead == '*') ADVANCE(55);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_KEYWORD_docclass);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_KEYWORD_importpkg);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_KEYWORD_useenv);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_multiline_comment);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 9},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 6},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_KEYWORD_docclass] = ACTIONS(1),
    [sym_KEYWORD_importpkg] = ACTIONS(1),
    [sym_KEYWORD_useenv] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_multiline_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_vesti_content] = STATE(65),
    [sym_statement] = STATE(2),
    [sym_docclass_decl] = STATE(16),
    [sym_singlepkg_decl] = STATE(16),
    [sym_multipkg_decl] = STATE(16),
    [sym_env_decl] = STATE(16),
    [aux_sym_vesti_content_repeat1] = STATE(2),
    [sym_KEYWORD_docclass] = ACTIONS(5),
    [sym_KEYWORD_importpkg] = ACTIONS(7),
    [sym_KEYWORD_useenv] = ACTIONS(9),
    [sym_line_comment] = ACTIONS(3),
    [sym_multiline_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      sym_KEYWORD_docclass,
    ACTIONS(7), 1,
      sym_KEYWORD_importpkg,
    ACTIONS(9), 1,
      sym_KEYWORD_useenv,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    STATE(3), 2,
      sym_statement,
      aux_sym_vesti_content_repeat1,
    STATE(16), 4,
      sym_docclass_decl,
      sym_singlepkg_decl,
      sym_multipkg_decl,
      sym_env_decl,
  [27] = 7,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_KEYWORD_docclass,
    ACTIONS(18), 1,
      sym_KEYWORD_importpkg,
    ACTIONS(21), 1,
      sym_KEYWORD_useenv,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    STATE(3), 2,
      sym_statement,
      aux_sym_vesti_content_repeat1,
    STATE(16), 4,
      sym_docclass_decl,
      sym_singlepkg_decl,
      sym_multipkg_decl,
      sym_env_decl,
  [54] = 6,
    ACTIONS(24), 1,
      anon_sym_LBRACE,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    STATE(5), 2,
      sym_env_arg,
      aux_sym_env_decl_repeat1,
    STATE(30), 2,
      sym_mandantory_arg,
      sym_optional_arg,
  [76] = 6,
    ACTIONS(30), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    STATE(5), 2,
      sym_env_arg,
      aux_sym_env_decl_repeat1,
    STATE(30), 2,
      sym_mandantory_arg,
      sym_optional_arg,
  [98] = 6,
    ACTIONS(26), 1,
      anon_sym_LPAREN,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    STATE(4), 2,
      sym_env_arg,
      aux_sym_env_decl_repeat1,
    STATE(30), 2,
      sym_mandantory_arg,
      sym_optional_arg,
  [120] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(40), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [133] = 4,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_options,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(42), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [150] = 4,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym_options,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(46), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [167] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(48), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [180] = 6,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(50), 1,
      anon_sym_COMMA,
    ACTIONS(52), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      sym_options,
    STATE(44), 1,
      aux_sym_multipkg_decl_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [200] = 6,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    ACTIONS(56), 1,
      aux_sym_options_token1,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    STATE(13), 1,
      aux_sym_options_repeat1,
    STATE(29), 1,
      aux_sym_options_repeat2,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [220] = 4,
    ACTIONS(64), 1,
      aux_sym_options_token1,
    STATE(13), 1,
      aux_sym_options_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(62), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [235] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [246] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [257] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(71), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [268] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [279] = 4,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    STATE(50), 1,
      sym_options,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(75), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [294] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(77), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [305] = 4,
    ACTIONS(56), 1,
      aux_sym_options_token1,
    STATE(13), 1,
      aux_sym_options_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(79), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [320] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(81), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [331] = 4,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    STATE(60), 1,
      sym_options,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(83), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [346] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(85), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [357] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(87), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [368] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(89), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [379] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(91), 4,
      ts_builtin_sym_end,
      sym_KEYWORD_docclass,
      sym_KEYWORD_importpkg,
      sym_KEYWORD_useenv,
  [390] = 4,
    ACTIONS(93), 1,
      aux_sym_optional_arg_token1,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_optional_arg_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [404] = 4,
    ACTIONS(97), 1,
      aux_sym_optional_arg_token1,
    ACTIONS(99), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      aux_sym_optional_arg_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [418] = 4,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_options_repeat2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [432] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(105), 3,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [442] = 4,
    ACTIONS(107), 1,
      anon_sym_LF,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    ACTIONS(111), 1,
      sym_class_pkg_name,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [456] = 4,
    ACTIONS(111), 1,
      sym_class_pkg_name,
    ACTIONS(113), 1,
      anon_sym_LF,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [470] = 4,
    ACTIONS(117), 1,
      anon_sym_COMMA,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      aux_sym_multipkg_decl_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [484] = 4,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      aux_sym_multipkg_decl_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [498] = 4,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    ACTIONS(126), 1,
      aux_sym_mandantory_arg_token1,
    STATE(48), 1,
      aux_sym_mandantory_arg_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [512] = 4,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    ACTIONS(130), 1,
      aux_sym_env_decl_token1,
    STATE(36), 1,
      aux_sym_env_decl_repeat2,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [526] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(133), 3,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [536] = 4,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    ACTIONS(137), 1,
      aux_sym_mandantory_arg_token1,
    STATE(38), 1,
      aux_sym_mandantory_arg_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [550] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(140), 3,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [560] = 4,
    ACTIONS(142), 1,
      aux_sym_optional_arg_token1,
    ACTIONS(145), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_optional_arg_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [574] = 4,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(149), 1,
      aux_sym_env_decl_token1,
    STATE(36), 1,
      aux_sym_env_decl_repeat2,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [588] = 4,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym_multipkg_decl_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [602] = 4,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      aux_sym_options_repeat2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [616] = 4,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      aux_sym_multipkg_decl_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [630] = 4,
    ACTIONS(149), 1,
      aux_sym_env_decl_token1,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      aux_sym_env_decl_repeat2,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [644] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(162), 3,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [654] = 4,
    ACTIONS(111), 1,
      sym_class_pkg_name,
    ACTIONS(164), 1,
      anon_sym_LF,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [668] = 4,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(170), 1,
      aux_sym_mandantory_arg_token1,
    STATE(38), 1,
      aux_sym_mandantory_arg_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [682] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(172), 3,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [692] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(83), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [701] = 3,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    ACTIONS(176), 1,
      sym_class_pkg_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [712] = 3,
    ACTIONS(178), 1,
      aux_sym_options_token1,
    STATE(12), 1,
      aux_sym_options_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [723] = 3,
    ACTIONS(180), 1,
      aux_sym_env_decl_token1,
    STATE(45), 1,
      aux_sym_env_decl_repeat2,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [734] = 3,
    ACTIONS(182), 1,
      anon_sym_LBRACE,
    ACTIONS(184), 1,
      sym_class_pkg_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [745] = 3,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    ACTIONS(176), 1,
      sym_class_pkg_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [756] = 3,
    ACTIONS(186), 1,
      aux_sym_options_token1,
    STATE(20), 1,
      aux_sym_options_repeat1,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [767] = 3,
    ACTIONS(176), 1,
      sym_class_pkg_name,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [778] = 3,
    ACTIONS(190), 1,
      aux_sym_env_decl_token1,
    STATE(41), 1,
      aux_sym_env_decl_repeat2,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [789] = 3,
    ACTIONS(111), 1,
      sym_class_pkg_name,
    ACTIONS(192), 1,
      anon_sym_LF,
    ACTIONS(60), 2,
      sym_line_comment,
      sym_multiline_comment,
  [800] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
    ACTIONS(194), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [809] = 2,
    ACTIONS(196), 1,
      sym_env_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [817] = 2,
    ACTIONS(198), 1,
      sym_class_pkg_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [825] = 2,
    ACTIONS(200), 1,
      sym_class_pkg_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [833] = 2,
    ACTIONS(176), 1,
      sym_class_pkg_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
  [841] = 2,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_multiline_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 76,
  [SMALL_STATE(6)] = 98,
  [SMALL_STATE(7)] = 120,
  [SMALL_STATE(8)] = 133,
  [SMALL_STATE(9)] = 150,
  [SMALL_STATE(10)] = 167,
  [SMALL_STATE(11)] = 180,
  [SMALL_STATE(12)] = 200,
  [SMALL_STATE(13)] = 220,
  [SMALL_STATE(14)] = 235,
  [SMALL_STATE(15)] = 246,
  [SMALL_STATE(16)] = 257,
  [SMALL_STATE(17)] = 268,
  [SMALL_STATE(18)] = 279,
  [SMALL_STATE(19)] = 294,
  [SMALL_STATE(20)] = 305,
  [SMALL_STATE(21)] = 320,
  [SMALL_STATE(22)] = 331,
  [SMALL_STATE(23)] = 346,
  [SMALL_STATE(24)] = 357,
  [SMALL_STATE(25)] = 368,
  [SMALL_STATE(26)] = 379,
  [SMALL_STATE(27)] = 390,
  [SMALL_STATE(28)] = 404,
  [SMALL_STATE(29)] = 418,
  [SMALL_STATE(30)] = 432,
  [SMALL_STATE(31)] = 442,
  [SMALL_STATE(32)] = 456,
  [SMALL_STATE(33)] = 470,
  [SMALL_STATE(34)] = 484,
  [SMALL_STATE(35)] = 498,
  [SMALL_STATE(36)] = 512,
  [SMALL_STATE(37)] = 526,
  [SMALL_STATE(38)] = 536,
  [SMALL_STATE(39)] = 550,
  [SMALL_STATE(40)] = 560,
  [SMALL_STATE(41)] = 574,
  [SMALL_STATE(42)] = 588,
  [SMALL_STATE(43)] = 602,
  [SMALL_STATE(44)] = 616,
  [SMALL_STATE(45)] = 630,
  [SMALL_STATE(46)] = 644,
  [SMALL_STATE(47)] = 654,
  [SMALL_STATE(48)] = 668,
  [SMALL_STATE(49)] = 682,
  [SMALL_STATE(50)] = 692,
  [SMALL_STATE(51)] = 701,
  [SMALL_STATE(52)] = 712,
  [SMALL_STATE(53)] = 723,
  [SMALL_STATE(54)] = 734,
  [SMALL_STATE(55)] = 745,
  [SMALL_STATE(56)] = 756,
  [SMALL_STATE(57)] = 767,
  [SMALL_STATE(58)] = 778,
  [SMALL_STATE(59)] = 789,
  [SMALL_STATE(60)] = 800,
  [SMALL_STATE(61)] = 809,
  [SMALL_STATE(62)] = 817,
  [SMALL_STATE(63)] = 825,
  [SMALL_STATE(64)] = 833,
  [SMALL_STATE(65)] = 841,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vesti_content, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vesti_content_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vesti_content_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vesti_content_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vesti_content_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_env_decl_repeat1, 2, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_env_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_env_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_options, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singlepkg_decl, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_docclass_decl, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_options, 4, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_options_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_options_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singlepkg_decl, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multipkg_decl, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multipkg_decl, 8, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multipkg_decl_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env_decl, 5, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_options_repeat2, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multipkg_decl, 6, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multipkg_decl_repeat1, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_docclass_decl, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env_decl, 6, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multipkg_decl, 7, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multipkg_decl, 5, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_env_arg, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multipkg_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_env_decl_repeat2, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_env_decl_repeat2, 2, 0, 0), SHIFT_REPEAT(36),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mandantory_arg, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_mandantory_arg_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mandantory_arg_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_arg, 3, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_optional_arg_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_optional_arg_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_options_repeat2, 2, 0, 0), SHIFT_REPEAT(56),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_options_repeat2, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mandantory_arg, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optional_arg, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multipkg_decl_repeat1, 4, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [202] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vesti(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "vesti",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
